# yaml-language-server: $schema=https://raw.githubusercontent.com/woodruffw/zizmor/main/support/zizmor.schema.json

rules:
  template-injection:
    ignore:
      - release_choco.yml
      - release_github.yml:107
      - release_github.yml:293
      - release_github.yml:389
      - release_github.yml:428
      - release_sub_homebrew.yml:32
      - release_sub_homebrew.yml:59
      - release_sub_homebrew.yml:72
      - release_sub_homebrew.yml:75
      - release_sub_pages.yml:66
      - release_sub_pages.yml:94
      - release_sub_pages.yml:102
      - release_sub_scoop.yml:32
      - release_sub_scoop.yml:55
      - release_sub_scoop.yml:82
      - release_sub_scoop.yml:107
      - release_sub_scoop.yml:110
      - release_playground.yml
