# yaml-language-server: $schema=https://raw.githubusercontent.com/woodruffw/zizmor/main/support/zizmor.schema.json

rules:
  template-injection:
    ignore:
      - release_choco.yml
      - release_github.yml:94
      - release_github.yml:301
      - release_github.yml:328
      - release_github.yml:366
      - release_sub_homebrew.yml:29
      - release_sub_homebrew.yml:56
      - release_sub_homebrew.yml:69
      - release_sub_homebrew.yml:72
      - release_sub_pages.yml:41
      - release_sub_pages.yml:69
      - release_sub_pages.yml:77
      - release_sub_scoop.yml:29
      - release_sub_scoop.yml:52
      - release_sub_scoop.yml:79
      - release_sub_scoop.yml:104
      - release_sub_scoop.yml:107
      - release_playground.yml
