# yaml-language-server: $schema=https://raw.githubusercontent.com/woodruffw/zizmor/main/support/zizmor.schema.json

rules:
  template-injection:
    ignore:
      - release_choco.yml
      - release_github.yml:87
      - release_github.yml:280
      - release_github.yml:311
      - release_github.yml:339
      - release_github.yml:347
      - release_github.yml:377
      - release_github.yml:415
      - release_github.yml:501
      - release_github.yml:528
      - release_github.yml:541
      - release_github.yml:544
      - release_github.yml:561
      - release_github.yml:584
      - release_github.yml:611
      - release_github.yml:636
      - release_github.yml:639
      - release_playground.yml
