name: OpenBSD (Subworkflow)

on:
  workflow_call:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: OpenBSD (QEMU)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        id: filter
        with:
          filters: |
            rust:
              - '**/*.rs'
              - '**/Cargo.toml'
              - '**/Cargo.lock'
              - '.cirrus.star'
              - '.github/workflows/main.yml'
              - '.github/workflows/sub_openbsd.yml'
              - '.cargo/**'
              - 'src/**'
              - 'tests/**'
              - '.github/scripts/smoke-test.sh'

      - name: Test on OpenBSD
        if: steps.filter.outputs.rust == 'true'
        uses: vmactions/openbsd-vm@86cdc08415d9d0865267e686561e276c52d62530 # v1.4.7
        with:
          release: "7.9"
          usesh: true
          prepare: |
            pkg_add rust
          run: |
            cargo build --locked
            cargo test --locked
