name: Reproducible FreeBSD tooling (Subworkflow)

on:
  workflow_call:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  freebsd_tools:
    name: Build FreeBSD tools
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: ${{ github.sha }}
          persist-credentials: false

      - name: Setup Zigbuild
        uses: $/.github/actions/setup-zigbuild
        with:
          target: x86_64-unknown-freebsd
          rust_components: rust-src
          install_target: "true"
          use_cache: "false"

      - name: Install cargo-clone
        run: |
          /home/linuxbrew/.linuxbrew/bin/brew install --force-bottle cargo-clone
          echo "/home/linuxbrew/.linuxbrew/bin" >> "$GITHUB_PATH"

      - name: Download tool sources
        run: cargo clone cargo-zigbuild@0.23.2 cargo-auditable@0.7.5 -- freebsd-tool-sources/

      - name: Cross-compile cargo-zigbuild
        run: |
          cargo zigbuild --locked --release --bin cargo-zigbuild --target x86_64-unknown-freebsd \
            --manifest-path freebsd-tool-sources/cargo-zigbuild/Cargo.toml \
            --target-dir "$GITHUB_WORKSPACE/freebsd-tools-build"

      - name: Cross-compile cargo-auditable
        run: |
          cargo zigbuild --locked --release --bin cargo-auditable --target x86_64-unknown-freebsd \
            --manifest-path freebsd-tool-sources/cargo-auditable/Cargo.toml \
            --target-dir "$GITHUB_WORKSPACE/freebsd-tools-build"

      - name: Upload FreeBSD tools
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: freebsd-tools-x86_64
          path: |
            freebsd-tools-build/x86_64-unknown-freebsd/release/cargo-zigbuild
            freebsd-tools-build/x86_64-unknown-freebsd/release/cargo-auditable
          retention-days: 1
          if-no-files-found: error
