name: Test RISC-V 64 (Subworkflow)

on:
  workflow_call:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test on Debian 13 (${{ matrix.target }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - riscv64gc-unknown-linux-gnu
          - riscv64gc-unknown-linux-musl
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Download celq binary
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: celq-${{ matrix.target }}
          path: ./bin

      - name: Test on Debian
        uses: vmactions/debian-vm@389ba1da28ff5b440cba52db8e03fc2e08e2affa # v1.0.0
        with:
          release: "13"
          arch: riscv64
          run: |
            chmod +x ./bin/celq
            sh .github/scripts/smoke-test.sh ./bin/celq
